<a href="https://colab.research.google.com/github/CamiloLon/Metodos_Computacionales_taller/blob/main/Tareas/Entrega_tareas_2021/1000417189/sesion_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

2. Un proceso para encriptar un mensaje secreto es usar cierta matrix cuadrada cuyos elementos son enteros con elementos enteros en la inversa. Se recibe un mensaje, se asigna un número a cada letra Por ejemplo, A=1, B=2, C=3, ... etc y espacio=27), se arreglan los números en una matriz de izquierda a derecha en cada fila, donde el número de elementos en la fila es igual al tamano de la matriz de codigo, se multiplica esa matriz por la matriz de código por la derecha, se transcribe el mensaje en una cadena de números y se manda el mensaje. 

La persona que debe recibir el mensaje conoce la matriz de codigo. El o ellla arrelgan el mensaje encriptado en una matriz de izquierda a derecha en cada fila, en donde el numero de elementos en una fila conicide con el tamano de la matriz de codigo muplicada por la derecha, por el inverso de la matriz de código y puede leer mensaje decodificado.

Usted a recibido el siguiente mensaje que fue encriptado usando la matriz A. Decodifiquelo.

```
A = matrix([[ 1,  2, -3,  4,  5],
        [-2, -5,  8, -8, -9],
        [ 1,  2, -2,  7,  9],
        [ 1,  1,  0,  6, 12],
        [ 2,  4, -6,  8, 11]])
```

Mensaje

47,49,-19,257,487,10,-9,63,137,236, 79,142,-184,372,536,59,70,-40,332,588, 

la primera fila del mensaje es 47,49,-19,257,487

¿Cual es el mensaje?

In [ ]:
A = np.array([[ 1,  2, -3,  4,  5],
        [-2, -5,  8, -8, -9],
        [ 1,  2, -2,  7,  9],
        [ 1,  1,  0,  6, 12],
        [ 2,  4, -6,  8, 11]])

In [ ]:
B = np.array([[ 47,  49, -19,  257,  487],
        [10,-9,63,137,236],
        [ 79,142,-184,372,536],
        [ 59,70,-40,332,588]])

In [ ]:
I = np.linalg.inv(A)

In [ ]:
M = np.dot(B,I)

In [ ]:
ABCD = {1:'A',2:'B',3:'C',4:'D',5:'E',6:'F',7:'G',8:'H',9:'I',10:'J',11:'K',12:'L',13:'M',
        14:'N',15:'O',16:'P',17:'Q',18:'R',19:'S',20:'T',21:'U',22:'V',23:'W',24:'X',25:'Y',
        26:'Z',27:' '}

text = ''
for i in range(M.shape[0]):
  for j in range(M.shape[1]):
    text += ABCD[M[i,j].round()]
print(text)

ARE YOU HAVING FUN  


3. Construir un programa que permita realizar la multiplicacion de dos matrices. El programa debe establecer si las matrices se pueden multiplicar.


In [ ]:
def producto_matrices(M1,M2):
  """
  M1: es la matriz izquierda
  M2: es la maatriz derecha
  """
  try:
    M1 = np.asarray(M1)
    M2 = np.asarray(M2)

    M3 = np.zeros((M1.shape[0],M2.shape[1]))
    for i in range(M1.shape[0]):
      fila = M1[i]
      for j in range(M2.shape[1]):
        columna = M2[:,j]
        M3[i,j] = (fila*columna).sum()
    return M3
  except TypeError:
    return "No se pueden multiplicar estas matrices"
  except ValueError:
    return "No se pueden multiplicar estas matrices"

In [ ]:

M1 = np.array([[2,2],[2,2],[1,1]])
print(M1)
print(M1.shape)
M2 = np.array([[1,0],[0,1]])
print(M2)
print(M2.shape)

[[2 2]
 [2 2]
 [1 1]]
(3, 2)
[[1 0]
 [0 1]]
(2, 2)


In [ ]:
producto_matrices(M1,M2)

array([[2., 2.],
       [2., 2.],
       [1., 1.]])

In [ ]:
M1 @ M2

array([[2, 2],
       [2, 2],
       [1, 1]])